[france_travail]
client_id = "PAR_apppostule_49530440805ac1f88db4588bd72d91d8ed03be4b3702483e7adf480ef6534aed"
client_secret = "bf354838ad72f27bd2a478978091ea7db28d19a861ecb45d81aa78005be749df"

[mail]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "gomisnicas@gmail.com"
smtp_password = "Gomes.96"  # mot de passe d’application
from_name = "Nicolas Gomes"
daily_limit = 10

[profile]
full_name = "Nicolas Dasylva GOMES"
title = "Data Engineer | DataOps | Big Data & Cloud"
location = "Lyon, France"
phone = "07 50 08 81 60"
email = "gomesnikas@gmail.com"
linkedin = ""
