[france_travail]
client_id = "PUT_CLIENT_ID"
client_secret = "PUT_CLIENT_SECRET"

[mail]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "gomisnicas@gmail.com"
smtp_password = "Gomes.96"  # mot de passe d’application
from_name = "Nicolas Gomes"
daily_limit = 10

[profile]
full_name = "Nicolas Dasylva GOMES"
title = "Data Engineer | DataOps | Big Data & Cloud"
location = "Lyon, France"
phone = "07 50 08 81 60"
email = "gomesnikas@gmail.com"
linkedin = ""
